# Generated by Django 3.2.9 on 2021-12-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.groupofhabits')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekOfHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('monday_hours', models.FloatField(blank=True, default=0)),
                ('tuesday', models.BooleanField(default=False)),
                ('tuesday_hours', models.FloatField(blank=True, default=0)),
                ('wednesday', models.BooleanField(default=False)),
                ('wednesday_hours', models.FloatField(blank=True, default=0)),
                ('thursday', models.BooleanField(default=False)),
                ('thursday_hours', models.FloatField(blank=True, default=0)),
                ('friday', models.BooleanField(default=False)),
                ('friday_hours', models.FloatField(blank=True, default=0)),
                ('saturday', models.BooleanField(default=False)),
                ('saturday_hours', models.FloatField(blank=True, default=0)),
                ('sunday', models.BooleanField(default=False)),
                ('sunday_hours', models.FloatField(blank=True, default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
